### ISSUE TITLE
Bookmark no longer works

### ISSUE THREAD

**Issue by Illuvatar118** [ploopyco/realm-generator#14]
Hello. I absolutely love this application and was using it for my worldbuilding when it suddenly stopped working. Now every time I click the bookmark, travel to the original reddit post, or click the link on this site it gives me the same message, "There's nothing here, yet." It's like it just vanished. Any help would be greatly appreciated. Thanks!
![Screenshot (52)](https://user-images.githubusercontent.com/121568856/209841696-08b4c683-b3bb-4055-92cc-c23291160cb6.png)

**Comment by OvadMarton** [comment]
Most likely because it was hosted on Heroku free tier, and Heroku discontinued the free tier.

**Comment by OvadMarton** [comment]
@Illuvatar118 Deployed in a new place: realm-generator-production.up.railway.app
I have no idea how much the free tier allows, kind of a test run for now.

**Comment by LeBigFish** [comment]
Both links appear to be no longer be working, with the latest link saying that the app is not responding. I also tried to build it in python but it seems broken for python 3.10. Definitely looks to be a cool tool, shame I'm not technical enough to get it working (though I'll try getting a 3.0 version of python running at some point to try)

**Comment by OvadMarton** [comment]
Yeah, you are correct. Railway also removed their free tier a few months ago.

**Comment by matthijs2222** [comment]
Has someone found a link already? I love this project and i use it for my rpg

**Comment by ploopyco** [comment]
New link is here: https://realm-generator.onrender.com/
